spring:
  application:
    name: msvc-auth
  profiles:
    active: ${PROFILE:dev}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
    port: ${PORT:8080}
jwt:
  secret: julio-secret